// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExcalidrawItemTemplates
{
    internal sealed partial class Vsix
    {
        public const string Id = "bf72d2ea-c4f6-494f-9090-b991100cd206";
        public const string Name = "Excalidraw";
        public const string Description = @"Add and edit Excalidraw diagrams inside Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "0.1.0";
        public const string Author = "Philip Hendry";
        public const string Tags = "";
    }
}
