// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExcalidrawInVisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidExcalidrawInVisualStudioPackageString = "abcd570c-4efd-4029-9deb-13a2dc2cef7a";
        public static Guid guidExcalidrawInVisualStudioPackage = new Guid(guidExcalidrawInVisualStudioPackageString);

        public const string guidExcalidrawInVisualStudioPackageCmdSetString = "49736e4b-0493-4438-8a8a-9be400c3d857";
        public static Guid guidExcalidrawInVisualStudioPackageCmdSet = new Guid(guidExcalidrawInVisualStudioPackageCmdSetString);

        public const string guidImagesString = "9d6d754e-a90f-4146-9efa-7c90303f36bb";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}