// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExcalidrawInVisualStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "10bf6342-1b19-4049-a8bf-6d7b763e4f38";
        public const string Name = "Excalidraw";
        public const string Description = @"An extension for adding Excalidraw diagrams to Visual Studio and edit them.";
        public const string Language = "en-US";
        public const string Version = "0.1.0";
        public const string Author = "Philip Hendry";
        public const string Tags = "";
    }
}
