// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExcalidrawInVisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EditorFactoryString = "abcd570c-4efd-4029-9deb-13a2dc2cef7a";
        public static Guid EditorFactory = new Guid(EditorFactoryString);

        public const string ExcalidrawEditorString = "abcd570c-4efd-4029-9deb-13a2dc2cef7a";
        public static Guid ExcalidrawEditor = new Guid(ExcalidrawEditorString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {

    }
}